title: Kitty May
description: Sex educator and facilitator
baseurl: ""
url: "http://kittymay.com"

markdown: kramdown
collections:
  - work_types

gems: [bourbon, neat]

exclude: [vendor]

contentful:
  spaces:
    - kittymay:
        space:        ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
